# Generated by Django 2.2.27 on 2022-04-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.TextField(default='Nameless'),
            preserve_default=False,
        ),
    ]
