name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
    - name: Heroku Action
      # You may pin to the exact commit or the version.
      # uses: CDNievas/heroku-action@c9cf9c85571e67583e44ec92c0d1113f66b0e838
      uses: CDNievas/heroku-action@v1.0
      with:
        # Used for authentication. You can find it in your heroku homepage account settings
        heroku_api_key: b50f3b27-3356-42be-8f68-aadf2a313570
        # Email from Heroku Account
        heroku_email: jflusche0717@bakercharters.org
        # The appname to use for deploying/updating
        heroku_app_name: wj9
        # The branch that you would like to deploy to Heroku
        branch: main # optional, default is HEAD
        # Set this to true if want to use --force
        useforce: false # optional
        # Set if your app is located in a subdirectory.
        appdir: # optional, default is 
        # Contents of the Procfile to save and deploy
        procfile: # optional, default is 
        # Set to true if you need upload files generated dynamically by the GitHub Action to Heroku
        dynamicFiles: # optional
        # Buildpacks to install on Heroku
        buildpacks: # optional, default is 
        # Path to an localized env file
        env_file: # optional, default is 
